on:
  pull_request:
    branches: ['*']
  push:
    branches: ['main']
  schedule:
  - cron: "18 18 * * 1"

jobs:
  selfcheck:
    name: Test Action
    strategy:
      matrix:
        runner: [ubuntu-22.04, ubuntu-24.04, ubuntu-latest]
        version: [latest, 9.5.1, 10.0.0]
    runs-on: ${{ matrix.runner }}
    steps:
      # To use this repository's private action,
      # you must check out the repository
      - name: Checkout
        uses: actions/checkout@v4
      - uses: ./
        with:
          version: ${{matrix.version}}
  lint-with-pre-commit:
    runs-on: ubuntu-24.04
    name: Lint with pre-commit
    steps:
    - uses: actions/checkout@v4
    - uses: actions/setup-python@v5
    - uses: instrumentl/pre-commit-action@v4
